package com.vbartere.Shared.Kafka.Enum;

public enum UserEventType {
    USER_CREATED,
    USER_UPDATED,
    USER_LOGIN,
    USER_DELETED,
    USER_BANNED,
    USER_REMOVE_YOUR_ADVERTISEMENT,
    USER_ADD_ADVERTISEMENT_TO_CART,
    USER_REMOVE_ADVERTISEMENT_FROM_CART,
    USER_PURCHASED_ADVERTISEMENT,
}
