package com.vbartere.Shared.Kafka.Enum;

public enum UserEventType {
    USER_CREATED,
    USER_UPDATED,
    USER_LOGIN,
    USER_DELETED,
    USER_BANNED,
    USER_REMOVE_HIS_ADVERTISEMENT,
    USER_CLEARED_HIS_CART,
    USER_DID_NOT_FIND_THE_ADVERTISEMENT,
    USER_ADD_ADVERTISEMENT_TO_CART,
    USER_REMOVE_ADVERTISEMENT_FROM_CART,
    USER_PURCHASED_ADVERTISEMENT,

}
